### ISSUE TITLE
Enable Rating on Components

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#11]
## Why Rating important?

With `Rating`, user can have a good understanding on Component's stability,maturity,etc...

## How

1. Pre-defined test cases with the help of tekton CI
2. Data colleciton on test cases
3. Auto data processing
4. balanced score syste

## How(With AI)

1. define rating prompts
2. Score given by AI

## Rating requirements

- [x] #116

## Tasks

- [x] #249
1.  Add a `ServiceAccount` named `pipelinerun-serviceaccount`
2. Add a `ClusterRole` named `pipelinerun-clusterrole`
3. Add a `ClusterRoleBinding` named `pipelinerun-clusterrolebinding`
4. Update `values.yaml`

```yaml
deployment:
    enable_rating: false
```
And writes this value to the environment variable `ENABLED_RATING` in the core's deployment.

This value is used to determine if the Rating controller logic is enabled. All subsequent changes depend on this variable.

- [x] #250
1. When a new repository is created, we need to check if there is a serviceaccount named `pipelinerun-serviceaccount` in the namespace, and if not, we need to create it.

2. When a new serviceaccount, i.e. (pipelinerun-serviceaccount) is created (other serviceaccounts are left alone), the serviceaccount needs to be bound to the clusterrolebinding (pipelinerun- clusterrolebidning)
If a pipelinerun-serviceaccount is deleted, you need to check if there are other repositories under this namespace, and if there are, you need to recreate the SA.

- [x] #251
1. Controls whether rating Controller is turned on or off based on environment variables.
2. Create pipelinerun based on RatingCR, collect all associated tasks, and write the information to status.
3. Implement a taskrun watcher that writes the results to the associated rating after the state of each taskrun changes.

**Comment by bjwswang** [comment]
Move to v0.0.2

**Comment by bjwswang** [comment]
## Rating requirements

- [ ] https://github.com/team-soteria/rback

**Comment by bjwswang** [comment]
@0xff-dev As discussed, we use tekton pipelines to run `Ratings` automatically and use a new CRD `Rating` to collection&summarize the results which means we need :

1. Develop a pipeline for rating
2. Store `pipelines` in ConfigMap upon `kubebb/core deployment`
3. Enable `Rating` for a `Repository` with a few settings and create the `pipelines`(cached in the ConfigMap) at repository namespace
4. Add new CRD `Rating` which watches on `Tektong PipelineRuns` and collect/summarize the pipelinerun results to its `status`

**Comment by 0xff-dev** [comment]
### Idea for implementation

- `Repository` supports automatic `Pipeline` creation. But only the Pipeline that comes with the system will be created automatically.
- `Repository` can be associated with multiple pipelines. Administrators can add some pipelines associated with `Repository`.
- `Users` can find a button one the detail page of component. When the user clicks the button, the pipelines associated with the component repository will be listed. Select some or all of the pipelines, and then create some `PipelineRuns` and a `Rating`.
- Each PipelineRun needs to be labeled to indicate which Component and Repository it belongs to, and each Rating CR needs to specify which Repository and Component it is associated with.
- Add new `rating controller`,  Select out all the `PipelineRuns` by the `Repository` and `Component` labeled in the CR and then count the information.
- **How to do information statistics?**

**Comment by 0xff-dev** [comment]
Based on the discussion, the administrator can create multiple Pipelines associated with the Repository while defining weights for these Pipelines. The data is stored into ConfigMap.

**Comment by 0xff-dev** [comment]
### Idea for implementation

- When Operator is deployed, a `ConfigMap` is created under the same namespace containing every yaml definition needed for the default full Pipeline.
- After a `Repository` is created, you need to determine whether its namespace contains the pipeline, tasks, and sa contained in the operator namespace. If sa, role, rolebinding have the same name, it can be overwritten directly.
- System Administration needs to define the weights for each Pipeline. The weight should be between 1 and 10 (if not defined, the default is 1).
- System administration fills in the parameters needed for each Pipeline as well as creating PipelineRun and Rating.
- Each PipelineRun has to have two labels identifying the name of the repository and the component.Rating also needs to have two fields or labels identifying the name of the repository and the component.
- The `Rating controller` needs to get the repository and component names from the Rating CR and then get the list of PipelineRuns. Then process the results of the PipelineRun calculations.

### Impl

- core's chart package is updated to add default pipeline definitions. Store the contents of these definitions into the ConfigMap
- Operator adds logic to determine if the CRDs needed by tekton are already installed in the cluster, and if they are, the following steps will be executed
- Changes to the Repository

    - Add function `CreatePipelineResources`
       This function reads all the yaml from ConfigMap and creates resources that do not exist in the namespace. Including pipeline, task, sa, role, rolebinding.
- Add an page to manage to configure the weight of each pipeline, which will be automatically converted to integer when calculated. Decimal numbers are not supported.
```yaml
kind: ConfigMap
data:
     "<pipeline-name>": "1"
```

- Rating CRD Definition
    
```go
type RatingSpec {
     RepoName string `json:"repoName"`
     ComponentName string `json:"componentName"`
} 

type RatingStatus {
       Rating float64 `json:"rating"`
       Reason string `json:"reason"`
}
```

Based on ComponentName and RepoName you can get the list of PipelineRuns.

Based on the execution result of each PipelineRun (success or failure) and the defined weights, the final score is obtained. Reasons are normally given via Reason.

- The repository controller requires one more process
watch The ConfigMap that stores the pipeline resources. If one of the pipeline resources changes, the corresponding namespace needs to be updated.

**Comment by bjwswang** [comment]
> * CreatePipelineResources
Great,This is good enough! 
Some tiny comments:
1. Use `CreateRatingResources` instead of `CreatePipelienResources`
2. `RatingStatus` should contain  the rating and reason for each rating pipeline

```golang
type RatingStatus struct {
        Rating float64 `json:"rating"`
       Reason string `json:"reason"`
       Data []
}

type RatingData struct {
      pipelineRef 


}
```

**Comment by 0xff-dev** [comment]
Rating CRD 

```go
type PipelineParam struct {
    PipelineName string

    // Introducing definitions from tekton
    Params tekton.Parmas
}
type RatingSpec struct {
    // Repository name
    RepoName string

    // Component Name
    ComponentName string
    PipelineParams []PipelineParam
}

type Result struct {
    // How many PipelineRun executions were successful?
    Success int 

    // List of names of failed PipelineRun executions
    FailedNames []string

    // The sum of the weights of the selected Pipeline
    TotalWeights int

    // Sum of weights of successfully executed PipelineRuns
    Weight int
}
type RatingStatus struct {
    Conditions []Condition
    Result
}
```

**Comment by 0xff-dev** [comment]
## Final Version

### CRD 

```go
//  PipelineParam Define the parameters required for each pipeline to run
type PipelineParam struct {
    PipelineName string
    Params tekton.Params
}

// Task Define the running result information of each Task to be collected by Rating.
type Task struct {
    Name string
    Type string
    
    // State three states, running, success, failure
    State int
    // Reason for failure
    Reason string
}

type RatingSpec struct {
    ComponentName string

    PipelineParams []PipelineParam
}

type RatingStatus struct {
    Tasks []Task
    // total weight of all tasks
    ExpectWeight int
    // The total weight of tasks that ran successfully
    ActualWeight int
}
```

### Impl Logic

1. Install Operator

1.1 The `kubebb-core` operator will come with a set of pipeline and tasks.  

1.2 Add `serviceaccount`,`clusterrole` and `clusterrolebinding` definitions

We defined `Rating` CRD, and operator will create `PipelineRun` resource according to the definition.
Each PipelineRun can specify the ServiceAccount at runtime, so our idea is that the `Repository Controller` creates a serviceaccount with the same name in each namespace containing the Repository, and binds it to the `clusterrolebinding`. Guaranteed runtime permissions for pipelinerun.

2. Repository

The Repository Controller needs to check whether the namespace contains a serviceaccount with the same name when the Repository is created, and if not, it needs to be created.

At the same time, **if the serviceaccount is deleted and there are other Repositories in the namespace**, then the serviceaccount needs to be created automatically.

3. Rating Controller

First of all, the `RatingController` needs to control whether it is enabled through an environment variable.
This is because, if the RatingController is enabled, the resources of the `tekton operator` need to be created. If these resources are not created, then the entire functionality is useless.

`RatingController` creates multiple PipelineRuns based on `spec.pipelineParams`.
At the same time, according to the name of each pipeline, get the list of tasks it contains and calculate the weight, and then write these data into status.

Finally, RatingController observes the running status of TaskRun and updates the result to the status of Rating.
