### ISSUE TITLE
kubebb/core support OCI helm repo

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#112]
how to use OCI helm repo in helm command: https://helm.sh/zh/docs/topics/registries/

One example about OCI helm repo: https://hub.docker.com/layers/abirdcfly/nginx/15.1.0/images/sha256-d9459e1206a4f5a8e0d7c5da8a306ab9b1ba5d7182ae671610b5699250ea45f8?context=explore
ref: https://docs.docker.com/docker-hub/oci-artifacts/

What we want:
- support OCI helm repo in CRD repository manifest and code logic
- add one test in example-test
- add example in website
- At first, we can just support OCI repo that doesn't require authentication.then, add auth in another pr

**Comment by Henry-Gao-2004** [comment]
@Abirdcfly Hi! I am learning Helm and OCI right now. Would you mind if I try to solve this issue?

**Comment by Abirdcfly** [comment]
https://github.com/helm/helm/issues/11000 some ref

**Comment by Abirdcfly** [comment]
> 2\. URI in the repo CRD be `oci://registry-1.docker.io/abirdcfly/nginx`, and the component just be `nginx`, which might require a Download and parse the version information via a `helm pull` like function or `skopeo list-tags` like function.

After offline discussion, we should implement this before considering other options.
