### ISSUE TITLE
helm install/upgrade should add auth args

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#114]

**Comment by zqq454224016** [comment]
according to the reading rules of secret.yaml , I changed value.yaml.

>   secret:
    # username for basic http authentication
    BASIC_AUTH_USER: 
    # password for basic http authentication
    BASIC_AUTH_PASS: 

then, I could still install chart without username and password. 
but after `kubectl describe pod`,I found that I didn't change the env of the container.

then I directly modified the env of the container
![image](https://github.com/kubebb/core/assets/59696261/2e076e4e-6fa1-43bd-b25f-92dcba98d7d0)
Even though the environment has changed，I could still install chart without username and password.
