### ISSUE TITLE
Achieve SLSA  in KubeBB

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#166]
As software supply chain is such important and critial, we need to enable SLSA in our Kubebb(especially kubebb/core). 

https://slsa.dev/

![image](https://github.com/kubebb/core/assets/30621793/eca6c07d-2972-4cc0-9420-f099f1ac843f)

## Threats in Supply chain

![image](https://github.com/kubebb/core/assets/30621793/8f275a08-fd44-46ff-9270-4aa4f61c56fd)

## SLSA Levels
- Levels https://slsa.dev/spec/v1.0/levels
- Detailed requirements on different SLSA Levels https://slsa.dev/spec/v1.0/requirements

## Discussions 

- [ ] SLSA v1.0 vs SLSA 0.1
- [ ] Our target SLSA level in kubebb/core(Level3)

## How to enable SLSA in kubebb

- [ ] 
- [ ] 

## Reference SLSA cases

- Go： https://go.dev/blog/supply-chain
- KubeEdge https://github.com/kubeedge/community/blob/master/sig-security/sig-security-audit/KubeEdge-security-audit-2022.pdf

**Comment by bjwswang** [comment]
With the help of tekton:
https://cd.foundation/blog/2023/05/31/getting-to-slsa-level-2-with-tekton-and-tekton-chains/

**Comment by Abirdcfly** [comment]
Inactive for a long time, close the issue
