### ISSUE TITLE
Add filter in repository 

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#19]
As discussed https://github.com/kubebb/core/issues/4#issuecomment-1564038535

**Comment by 0xff-dev** [comment]
```go
type RepositorySpec {
    // chart包对应的过滤条件，如果设置了这个字段，对于chart包名字不在这里的，不会保留。
    // 同时会根据version过滤版本。
    Filter map[string]FilterCond `json:"filter,omietmpy"`
}

type FilterCond struct {
    // 如果为True，则会过滤掉所有的废弃版本
    Deprecated bool `json:"deprecated,omitempty"`
    // 准确匹配version的某一项。
    Versions []string `json:"versions,omitempty"`
    // 通过正则匹配某些版本
    Regexp  string `json:"通过正则过滤"`
    // 小于某个特定版本的所有版本
    Less string `json:"less,omitempty"`
   // 大于某个特定版本的所有版本
   Greater string `json:"greater,omitempty"`
}
```
这几个条件的关系我的理解是 `Deprecated && (versions || regexp || less || greater)` 的关系

**Comment by bjwswang** [comment]
> ```go
> type RepositorySpec {
>     // chart包对应的过滤条件，如果设置了这个字段，对于chart包名字不在这里的，不会保留。
>     // 同时会根据version过滤版本。
>     Filter map[string]FilterCond `json:"filter,omietmpy"`
> }
> 
> type FilterCond struct {
>     // 如果为True，则会过滤掉所有的废弃版本
>     Deprecated bool `json:"deprecated,omitempty"`
>     // 准确匹配version的某一项。
>     Versions []string `json:"versions,omitempty"`
>     // 通过正则匹配某些版本
>     Regexp  string `json:"通过正则过滤"`
>     // 小于某个特定版本的所有版本
>     Less string `json:"less,omitempty"`
>    // 大于某个特定版本的所有版本
>    Greater string `json:"greater,omitempty"`
> }
> ```
> 
> 这几个条件的关系我的理解是 `Deprecated && (versions || regexp || less || greater)` 的关系

FilterCond中符合条件的Component保留

**Comment by 0xff-dev** [comment]
Filter字段不为空的时候，表示对目标chart包的版本过滤，不在其中的chart包会保留，不会对版本做任何过滤。
