### ISSUE TITLE
Find a more suitable codecov configuration

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#212]
不太确定是codecov的配置问题还是codecov的限制，看起来目前codecov的覆盖率只是把当前pr和main分支的代码做对比，这意味着，如果pr的代码不是基于最新main的代码来提交，就会出现实际代码覆盖率没有提高，但是显示代码覆盖率提高到情况。
比如 #195 显示的那样，看起来有`10.11% (+1.14%) compared to e4c0ba5`的提升，那只是因为#195还没有基于最新的代码做rebase。
所以要做的是：
1. 调查这个问题是codecov的配置不合理还是codecov的限制
2. 如果是codecov的限制，那么需要管理员在仓库设置中设置只有最新代码才能提交
3. 如果是codecov的配置错误，提交pr来修改。

![CleanShot 2023-08-04 at 14 35 59](https://github.com/kubebb/core/assets/5100555/d786e383-5425-4907-9bf6-a3f082f7e688)

---

Not quite sure if it's a codecov configuration issue or a codecov limitation, it looks like the current codecov coverage is just comparing the current pr to the code in the main branch, which means that if the pr code isn't committed based on the latest main code, there will be no increase in actual code coverage, but an increase in display code coverage.

For example, #195 shows that it has `10.11% (+1.14%) compared to e4c0ba5`, that's only because #195 hasn't done a rebase based on the newest code.

So there are some things to do: 
1. investigate if the problem is due to a misconfiguration of the codecov or to a limitation of the codecov. 
2. if it's due to a limitation of the codecov, then admin needs to set in repository settings that only latest code can be committed.
3. if codecov is misconfigured, submit pr to change it.

![CleanShot 2023-08-04 at 14 35 59](https://github.com/kubebb/core/assets/5100555/d786e383-5425-4907-9bf6-a3f082f7e688)

**Comment by bjwswang** [comment]
@Abirdcfly Thanks for all the suggestions. I have updated the branch protection rules to make sure 

`branches to be update to date before merging`
