### ISSUE TITLE
Optimize auto-sync release to component workflow

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#217]
> There's a flaw here, even a draft release will trigger auto-sync, which is a no-brainer because a release from draft to undraft won't trigger the github action...
It's ok. We only need to know there is a auto-sync happended upon a `release` even it's a draft.  One more important thing is : 
```
this auto-sync pr should be closed if  that release got removed. 
```

_Originally posted by @bjwswang in https://github.com/kubebb/components/issues/94#issuecomment-1667103030_

some ref: https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#release

**Comment by Abirdcfly** [comment]
So, we want:
1. create auto-sync pr when release **Officially** released.(event type is **released**: *A release was published, or a pre-release was changed to a release.*
2. According to the agreed open source rules, we shouldn't delete official releases, but our auto-sync can support close pr when deleting a release (low priority).

**Comment by bjwswang** [comment]
> 

If we can limit our `auto-sync` to `officially relesed releases`, it's ok pr not closed when release removed.

**Comment by bjwswang** [comment]
@Abirdcfly btw... this workflow is missing the webhooks

**Comment by Abirdcfly** [comment]
> this workflow is missing the webhooks

en...When this workflow is added, there is no webhook yet...

**Comment by bjwswang** [comment]
we can add webhooks firstly
