### ISSUE TITLE
duplicate check on portal's path/entry

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#225]
the path and entry shoud keep unique among the portals with webhook

**Comment by Henry-Gao-2004** [comment]
Tasks: 
When a new portal is added: 
1. check all past data to see if there is a duplicate
2. If there is a duplicate, mark condition and record which is the equivalent to the new one

**Comment by bjwswang** [comment]
Too many  changes if we use webhoo. We can add a controller for `Portal` .Do conflict check on `path & entry` and update the status to let people know a conflict is happening
