### ISSUE TITLE
Component adds annotations field

### ISSUE THREAD

**Issue by 0xff-dev** [kubebb/core#229]
Component adds annotations field.

We need to add some markup information to annotations, and currently the component definition is missing the annotations field.

```go
type ComponentStatus struct {
    ...
   Annotations map[string]string
}
```

**Comment by bjwswang** [comment]
See https://github.com/kubebb/components/pull/97

**Comment by bjwswang** [comment]
@dayuy Would you like to pick up this issue?

**Comment by dayuy** [comment]
Okay, distinguish between `public repo` and `internal chart museum` by what field? @bjwswang

**Comment by dayuy** [comment]
I see, there is no need to change `CRD Repository`, just add an annotation `component-store.kubebb.k8s.com.cn/source` when  fetching `index.yaml` from chart museum to create `Component`. 
The annotations in the `Chart.yaml` of the chart uploaded are set by the user, if not set, it cannot be determined.

**Comment by 0xff-dev** [comment]
> I see, there is no need to change `CRD Repository`, just add an annotation `component-store.kubebb.k8s.com.cn/source` when fetching `index.yaml` from chart museum to create `Component`. The annotations in the `Chart.yaml` of the chart uploaded are set by the user, if not set, it cannot be determined.

Agree with you. We just need to synchronize the annotations field of `chart.yaml` to `component`. For how to set up annotations, our platform should automatically tag the `chart package` with official.

However, `https://kubebb.github.io/components` is a repository that we maintain, but the chart packages it generates are not packaged from our platform, so we need to add a special treatment for this repository.

**Comment by 0xff-dev** [comment]
> > I see, there is no need to change `CRD Repository`, just add an annotation `component-store.kubebb.k8s.com.cn/source` when fetching `index.yaml` from chart museum to create `Component`. The annotations in the `Chart.yaml` of the chart uploaded are set by the user, if not set, it cannot be determined.
> 
> Agree with you. We just need to synchronize the annotations field of `chart.yaml` to `component`. For how to set up annotations, our platform should automatically tag the `chart package` with official.
> 
> However, `https://kubebb.github.io/components` is a repository that we maintain, but the chart packages it generates are not packaged from our platform, so we need to add a special treatment for this repository.

It would be better if the list of repositories that require special handling was customizable.

**Comment by bjwswang** [comment]
So we have common scenarios like this:

For compoenent developer,they can add any annotations in their `Chart.yaml`. But for this field `omponent-store.kubebb.k8s.com.cn/source`, we should allow `platform owner(who runs the kubebb)` customize the repository's component types.

For examples:

- if the system admin set repository `kubebb` as the `official repository`,all components in that repo should be treated as `official components`
- if the system admin set repository `mychartmuseum` as the `internal repository`, all components in that repo should be treaed as `internal components`

**Comment by dayuy** [comment]
Finally, we decide to just add annotations to `Repository` for now, indicating the repository `kubebb` is official.
