### ISSUE TITLE
INSTALLATION FAILED by timeout when using Helm

### ISSUE THREAD

**Issue by yihoyoung** [kubebb/core#234]
helm install --wait -nkubebb-system kubebb-core kubebb/kubebb-core
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
Error: INSTALLATION FAILED: timed out waiting for the condition

**Comment by Abirdcfly** [comment]
It looks like the helm install failed, which is usually the case when the image isn't pulled successfully ....

**Comment by yihoyoung** [comment]
It's solved.
I did fallowing steps.
1, pull helm chart package to local, and unpack. 
helm pull kubebb/kubebb-core
2. download docker images that in the helm chart files and push to local harbor.
3. update values.yaml file with image url in the local harbor.
4. update values.yaml file with storageclass name used in the local cluster.
5. helm install --wait -nkubebb-system kubebb-core kubebb/kubebb-core -f ./kubebb-core/values.yaml
