### ISSUE TITLE
Discuss: CRD manager

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#239]
(Created: 20230811 Document is time-sensitive）

# CRD Handling in Helm

https://github.com/helm/community/blob/main/hips/hip-0011.md
> Our current solution, while not comprehensive, is designed to privilege safety over flexibility

> ### The Core Problem
> The core problem is that CRDs (being a globally shared resource) are fragile. Once a CRD is installed, we typically have to assume (all other things being equal) that it is shared across namespaces and groups of users.
> For that reason, installing, modifying, and deleting CRDs is a process that has ramifications for all users and systems of that cluster.
> In spite of this, the Kubernetes API server is permissive about these CRDs. CRDs are mutable (even without a version change). When they are deleted, all instances of them are deleted without warning. They can be upgraded to be entirely incompatible with previous versions. And there is no way to programmatically inspect the CRDs in a cluster and determine whether they are used, how they are used, and by what.

https://github.com/helm/helm/issues/7735
https://github.com/helm/helm/issues/10585
https://github.com/helm/helm/issues/5871

# Existing solutions for other tools

## flux2

https://fluxcd.io/flux/components/helm/helmreleases/#crds

# Problems we encountered

# Problems encountered by others

**Comment by kvaps** [comment]
Heya, I just added some workaround plugin to solve this problem:
https://github.com/kvaps/helm-ensurecrds

**Comment by bjwswang** [comment]
> 

Hey @kvaps .Thanks for this quick suggestion.That's great! Here we are trying to fix `crd management` within a operator.  For this `kubebb/core`, you can simply treat this as a superset of helm(actually more than helm) but in Operator Pattern(declarative).

**Comment by Abirdcfly** [comment]
Inactive for a long time, close the issue
