### ISSUE TITLE
try to use `harbor` or `docker registry` to plan a OCI registry.

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#246]
@Abirdcfly @0xff-dev After this pr merged, I think we can try to use `harbor` or `docker registry` to plan a private OCI registry.

_Originally posted by @bjwswang in https://github.com/kubebb/core/issues/224#issuecomment-1676624164_

**Comment by Henry-Gao-2004** [comment]
For harbor, here are some websites that can be useful: 
harbor website: https://goharbor.io/
harbor installation guide: https://goharbor.io/docs/2.8.0/install-config/
harbor releases: https://github.com/goharbor/harbor/releases
harbor demo: https://demo.goharbor.io/harbor/projects
how to create projects and repositories: https://goharbor.io/docs/1.10/working-with-projects/create-projects/
