### ISSUE TITLE
OCI component cant get digest

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#252]
OCI component cant get digest can be fixed by other pr.

_Originally posted by @Abirdcfly in https://github.com/kubebb/core/issues/224#issuecomment-1669292089_

**Comment by Henry-Gao-2004** [comment]
I found two ways that might allow us to get the digest: 

skopeo inspect: skopeo uses a lot of methods that are not exported, and it can be hard to write our own code. 

helm registry/oras: oras also uses some local variables and methods. When I try to use the method to get the digest, an error "object required" is returned. 

Can I know if I can try to fix this issue?

**Comment by Henry-Gao-2004** [comment]
> Of course, you're welcome, so feel free to try it out.

Thank you! I will try my best to solve it!
