### ISSUE TITLE
Build core image with github action

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#34]
DOCKERHUB_USER kubebb

**Comment by bjwswang** [comment]
@Abirdcfly help with @Lanture1064

**Comment by Abirdcfly** [comment]
One of our previous examples:
- github action file here https://github.com/bestchains/fabric-operator/blob/main/.github/workflows/image-build.yaml
- Note that the above build **multi-architecture** image is **push commit** event triggered, that is, after the pr is **merged**, the normal test when the pr is **created** can be similar to the simple build amd64 image in this link. https://github.com/bestchains/fabric-operator/blob/7776e712f9ad0cd50847ed94c069fed9aea70e10/.github/workflows/endtoend-tests.yaml#L35-L39
- The specific commands to build the image can be seen in the makefile https://github.com/bestchains/fabric-operator/blob/7776e712f9ad0cd50847ed94c069fed9aea70e10/Makefile#L44

**Comment by bjwswang** [comment]
I will pick up this task since we need this immediately

**Comment by bjwswang** [comment]
this can be closed as pr https://github.com/kubebb/core/pull/50 merged
