### ISSUE TITLE
update update-helm-chart-version.sh

### ISSUE THREAD

**Issue by Abirdcfly** [kubebb/core#340]
> files not required anymore

yes. we need update https://github.com/kubebb/core/blob/main/.github/update-helm-chart-version.sh

_Originally posted by @Abirdcfly in https://github.com/kubebb/components/issues/121#issuecomment-1716968701_

please see kubebb/components#121 and kubebb/components#123

**Comment by bjwswang** [comment]
this can be marked as not planned any.
