### ISSUE TITLE
Tekton piepelineruns should support on-demand cleanup

### ISSUE THREAD

**Issue by Carrotzpc** [kubebb/core#364]
When publishing low-code applications, PipelineRuns and PVCs are generated, and they need to be cleaned up on demand.

![image](https://github.com/kubebb/core/assets/10265417/7c4a2fd0-6a25-4717-a273-2b32e62a896d)

related: #162

**Comment by bjwswang** [comment]
fixed as we can use  `volume claim template` to claim a volume and remove it when pipelinerun removed.

![image](https://github.com/kubebb/core/assets/30621793/c51cbe7a-cc30-4ca9-b121-e04a8a4693d3)
