### ISSUE TITLE
:bug: `RatingController` reconcile will always trigger when the RatingEnable of the Repository is false

### ISSUE THREAD

**Issue by 0xff-dev** [kubebb/core#368]
https://github.com/kubebb/core/blob/a1cbc9de67e835bb1cd02dd7dd010fadc17ff75b/controllers/rating_controller.go#L119
From the logic here, it will always return false, then Reconcile will always trigger.
I think we should revert to accepting update events from Rating.

**Comment by zqq454224016** [comment]
It changed in pr #363
