### ISSUE TITLE
Develop CRD Component

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#6]

**Comment by 0xff-dev** [comment]
component controller 的逻辑

1. 当 Component 创建的时候，需要判断是否含有 `kubebb.component.repository=<repository-name>` 的标签。如果不存在则需要添加
2. 当 Component 更新的时候，也是判断标签是否存在。
3. 可以被删除，但是后面可能会被repository的goroutine重新创建出来。

**Comment by 0xff-dev** [comment]
mysql和kubedashboard

**Comment by 0xff-dev** [comment]
operator的工作逻辑是，对于Component的创建，更新，删除事件做处理。
所以你首先需要的改动是：SetupWitManager函数，设置对Component的Create，Update，Delete的处理函数。
Create，Update，Delete这三个函数都是返回bool，表示是否需要进入到Reconcile函数的处理逻辑，返回true表示需要进入，如果不设置这几个函数，默认都是true，进入到Reconcile的处理逻辑。

component-operator就是检查目标Component是否存在目标标签。所以对于Create和Update我们需要判断，是否存在标签。

在Reconcile的逻辑中，给component添加上标签即可。
