### ISSUE TITLE
Develop CRD ComponentPlan(ArgoCD)

### ISSUE THREAD

**Issue by bjwswang** [kubebb/core#7]
Tasks:

- [ ] CRD ComponentPlan

Dependent tasks:

- [ ] #9 
- [ ] #10

**Comment by Abirdcfly** [comment]
https://argo-cd.readthedocs.io/en/stable/user-guide/helm argo use helm chart as a type of application, We can take a closer look at how they handle Helm charts.

**Comment by bjwswang** [comment]
we changed our design which no longer needs tekton during component development.
